### ISSUE TITLE
proton not working

### ISSUE THREAD

**Issue by RootShinobi** [obnoxiousish/async_twitter_api_client#5]
AsyncClient.__init__() got an unexpected keyword argument 'proton'

**Comment by obnoxiousish** [comment]
i’ll try and look into it in a little bit

**Comment by RootShinobi** [comment]
![image](https://github.com/obnoxiousish/async_twitter_api_client/assets/111008396/32ff5292-b57b-419d-8611-90f063086a60)
i think kwargs not for AsyncClient

**Comment by obnoxiousish** [comment]
it is because of changes i made, it needs to kwargs.pop somewhere or use an alternative to kwargs

**Comment by RootShinobi** [comment]
![image](https://github.com/obnoxiousish/async_twitter_api_client/assets/111008396/4dc5823b-03bc-43ba-b473-287c511c26f9)
![image](https://github.com/obnoxiousish/async_twitter_api_client/assets/111008396/e617c9b1-dba7-401f-941d-8e0b7cbc5706)
look what i found. u can use init kwargs as kwargs for the httpx client

**Comment by RootShinobi** [comment]
btw the structure of the client is very very strange

**Comment by obnoxiousish** [comment]
core issue is that you must be passing proton kwarg to asyncAuthenticate not __init__

**Comment by RootShinobi** [comment]
> core issue is that you must be passing proton kwarg to asyncAuthenticate not **init**

I do it
![image](https://github.com/obnoxiousish/async_twitter_api_client/assets/111008396/3736e556-d51d-4f09-b5cf-24479e5964bd)
![image](https://github.com/obnoxiousish/async_twitter_api_client/assets/111008396/8f321b42-83b9-48ae-9340-1a5dfa1d7c63)
![image](https://github.com/obnoxiousish/async_twitter_api_client/assets/111008396/26b1896e-1443-4f1e-a9a6-440feafb2b2b)

**Comment by RootShinobi** [comment]
I mean, perhaps it is better to accept the parameters for AsyncClient in the init of AsyncAccount?

**Comment by obnoxiousish** [comment]
there i added a patch to pop proton in asyncLogin
